### ISSUE TITLE
AXFR only gets one record

### ISSUE THREAD

**Issue by kevinior** [grifferz/ptrcheck-rs#8]
Using version 0.1.1 (built from commit 99ae50f3736ccffd233f2a6719b06afd00a65b82):

```
./ptrcheck -v --server 127.0.0.1 --zone caboose.org.uk
Connecting to 127.0.0.1 port 53 for AXFR of zone caboose.org.uk
Zone contains 1 record
Found 0 unique address (A/AAAA) records
```

but using dig I get more:

```
dig -t axfr caboose.org.uk @127.0.0.1

; <<>> DiG 9.18.28-1~deb12u2-Debian <<>> -t axfr caboose.org.uk @127.0.0.1
;; global options: +cmd
caboose.org.uk.         3600    IN      SOA     oelph.caboose.org.uk. postmaster.caboose.org.uk. 2021022102 14400 3600 604800 3600
...
caboose.org.uk.         300     IN      A       85.119.82.49
caboose.org.uk.         300     IN      AAAA    2001:ba8:1f1:f0e9::2
caboose.org.uk.         3600    IN      MX      10 mail.caboose.org.uk.
caboose.org.uk.         3600    IN      NS      a.authns.bitfolk.co.uk.
caboose.org.uk.         3600    IN      NS      b.authns.bitfolk.com.
caboose.org.uk.         3600    IN      NS      c.authns.bitfolk.com.
...
mail.caboose.org.uk.    300     IN      A       85.119.82.49
mail.caboose.org.uk.    300     IN      AAAA    2001:ba8:1f1:f0e9::2
oelph.caboose.org.uk.   3600    IN      A       85.119.82.49
oelph.caboose.org.uk.   3600    IN      AAAA    2001:ba8:1f1:f0e9::2
...
www.caboose.org.uk.     300     IN      A       85.119.82.49
www.caboose.org.uk.     300     IN      AAAA    2001:ba8:1f1:f0e9::2
caboose.org.uk.         3600    IN      SOA     oelph.caboose.org.uk. postmaster.caboose.org.uk. 2021022102 14400 3600 604800 3600
;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1) (TCP)
;; WHEN: Tue Nov 26 14:40:53 GMT 2024
;; XFR size: 20 records (messages 3, bytes 1267)
```

I captured the AXFR request from ptrcheck with tcpdump and looking at the response I see that there are two, one with just the SOA record and another with the rest.

**Comment by grifferz** [comment]
Thanks! I am able to reproduce this myself now so I will look more into it.

**Comment by kevinior** [comment]
Let me know if you need any more information.

**Comment by grifferz** [comment]
Out of interest what software is your name server?

**Comment by kevinior** [comment]
It's PowerDNS, version 4.7.3-2.

**Comment by grifferz** [comment]
Happily it seems I was doing it wrong after all!

[`query`](https://docs.rs/hickory-client/latest/hickory_client/client/trait.Client.html#method.query) method is meant for only a single response. There is a dedicated [`zone_transfer`](https://docs.rs/hickory-client/latest/hickory_client/client/trait.Client.html#method.zone_transfer) method which is a proper stream of responses. I was just (un)lucky that almost all AXFR fit in one response so it worked most of the time!

In a test program I've managed to use `zone_transfer` to AXFR your zone successfully.
